version: '3.9'

services:
  celery_app:
    build:
      context: ./celery
      dockerfile: Dockerfile
    container_name: celery
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./celery
    container_name: celery_worker
    command: celery -A celery_worker worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - celery_app

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rest:
    build: ./rest
    container_name: rest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - celery_app

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: