"""add transaction models

Revision ID: 4871a4bcf8a3
Revises: f554469d18d7
Create Date: 2024-03-12 20:14:20.380523

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4871a4bcf8a3'
down_revision: Union[str, None] = 'f554469d18d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expensetransactionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EXECUTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expensecategorymodel.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['useraccountmodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incometransactionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EXECUTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['useraccountmodel.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['incomesourcemodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfertransactionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EXECUTED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['useraccountmodel.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['useraccountmodel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfertransactionmodel')
    op.drop_table('incometransactionmodel')
    op.drop_table('expensetransactionmodel')
    # ### end Alembic commands ###
