from dotenv import load_dotenv
import os

load_dotenv()

DB_URL = os.getenv("DB_URL") or ""
SECRET_KEY = "AS_MUCH_AS_THIS_IS_A_BAD_EXAMPLE_OF_A_TOKEN_PYTHON_IS_JUST_AS_BAD_AT_TYPE_SAFETY_PLEASE_DO_NOT_USE_IT"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
BOOKS_SEARCH_COUNT_DEFAULT = 10
