"""deleted role from link

Revision ID: 1ccb4e4cdc9c
Revises: 5989ba8104ee
Create Date: 2024-03-04 12:58:41.342990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ccb4e4cdc9c'
down_revision: Union[str, None] = '5989ba8104ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
