"""deleted budget from link

Revision ID: 5989ba8104ee
Revises: ef92f0dd0a5d
Create Date: 2024-03-04 12:56:28.684073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5989ba8104ee'
down_revision: Union[str, None] = 'ef92f0dd0a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertriplink', 'budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertriplink', sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
