"""added budget to user-trip link

Revision ID: ef92f0dd0a5d
Revises: 7b19fe328bb1
Create Date: 2024-03-04 00:07:45.365955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef92f0dd0a5d'
down_revision: Union[str, None] = '7b19fe328bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertriplink', sa.Column('budget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertriplink', 'budget')
    # ### end Alembic commands ###
