FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN mount=type=cache,target=/root/.cache pip3 install -r requirements.txt
COPY . .

ENTRYPOINT [ "celery", "-A", "tasks", "worker", "--loglevel=INFO"]
