site_name: Web Development Tools Docs

theme:
  name: readthedocs

nav:
  - Lab1:
    - Главная страница: LR1/index.md
    - Аутентификация: LR1/auth.md
    - База данных: LR1/db.md
    - Эндпоинты: LR1/endpoints.md
    - Схемы: LR1/schemas.md
    - Приложение: LR1/main.md
    - Leetcode: LR1/leetcode.md
  - Lab2:
    - Главная страница: LR2/index.md
    - Задание: LR2/task.md
    - Leetcode: LR2/leetcode.md