"""skill added

Revision ID: a34252dffc1e
Revises: 
Create Date: 2024-04-14 03:05:28.607818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a34252dffc1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('balance_id', sa.Integer(), nullable=False))
    op.add_column('subscription', sa.Column('cost', sa.Float(), nullable=False))
    op.add_column('subscription', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'subscription', 'balance', ['balance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'start_time')
    op.drop_column('subscription', 'name')
    op.drop_column('subscription', 'cost')
    op.drop_column('subscription', 'balance_id')
    # ### end Alembic commands ###
