site_name: "Рашевский_Вячеслав_K33402_Лабораторная_работа"
nav:
  - "№1: Реализация серверного приложения FastAPI.":
      - index.md
      - task1.md
      - task2.md
      - task3.md
      - lab.md
      - leetcode.md