"""add import to script.py.mako

Revision ID: 65427cf84bac
Revises: bc177ef05efc
Create Date: 2024-05-11 21:34:39.136273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import *


# revision identifiers, used by Alembic.
revision: str = '65427cf84bac'
down_revision: Union[str, None] = 'bc177ef05efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
