"""add import to env.py

Revision ID: c63f5b777ca7
Revises: 65427cf84bac
Create Date: 2024-05-11 21:56:20.095478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import *


# revision identifiers, used by Alembic.
revision: str = 'c63f5b777ca7'
down_revision: Union[str, None] = '65427cf84bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
