version: '3.9'

services:
  web:
    build:
      context: ./Lr1
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  parser:
    build:
      context: ./Lr2/Task2/parser
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis

  db:
    container_name: db_container
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  celery_worker:
    build:
      context: ./Lr1
      dockerfile: Dockerfile
    command: celery -A travel_app.tasks worker --loglevel=info
    user: "1000:1000"
    depends_on:
      - redis
      - db

volumes:
  postgres_data: