"""skill removed

Revision ID: d9d9e30fa4f4
Revises: c6f4c9397087
Create Date: 2024-05-30 16:41:23.942388

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d9e30fa4f4'
down_revision: Union[str, None] = 'c6f4c9397087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skillwarriorlink', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skillwarriorlink', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
