"""readonly added

Revision ID: 01e666d81d67
Revises: 05caa3997387
Create Date: 2024-03-24 18:47:28.709286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01e666d81d67'
down_revision: Union[str, None] = '05caa3997387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'readonly')
    op.add_column('usersboardslink', sa.Column('readonly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersboardslink', 'readonly')
    op.add_column('board', sa.Column('readonly', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
