"""skill added

Revision ID: 244bdde14ae0
Revises: 05ba1e4cad87
Create Date: 2024-03-24 17:06:09.795263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '244bdde14ae0'
down_revision: Union[str, None] = '05ba1e4cad87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('longboard_board_id_fkey', 'longboard', type_='foreignkey')
    op.drop_column('longboard', 'board_id')
    op.drop_constraint('shortboard_board_id_fkey', 'shortboard', type_='foreignkey')
    op.drop_column('shortboard', 'board_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortboard', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shortboard_board_id_fkey', 'shortboard', 'board', ['board_id'], ['id'])
    op.add_column('longboard', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('longboard_board_id_fkey', 'longboard', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###
