"""skill added

Revision ID: 5edec548cef9
Revises: 7b553d50013c
Create Date: 2024-03-24 16:22:16.462944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5edec548cef9'
down_revision: Union[str, None] = '7b553d50013c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersboardslink', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersboardslink', 'id')
    # ### end Alembic commands ###
