"""skill added

Revision ID: a44f2f8eec93
Revises: 244bdde14ae0
Create Date: 2024-03-24 17:08:39.028614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a44f2f8eec93'
down_revision: Union[str, None] = '244bdde14ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('longboard', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'longboard', 'board', ['board_id'], ['id'])
    op.add_column('shortboard', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shortboard', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortboard', type_='foreignkey')
    op.drop_column('shortboard', 'board_id')
    op.drop_constraint(None, 'longboard', type_='foreignkey')
    op.drop_column('longboard', 'board_id')
    # ### end Alembic commands ###
