"""skill added

Revision ID: a9013c53c805
Revises: 
Create Date: 2024-03-23 16:52:14.262122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9013c53c805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('readonly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('longboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shortboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersboardslink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.create_table('longtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longboard_id', sa.Integer(), nullable=True),
    sa.Column('task_importance', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='importancechart'), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('task_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['longboard_id'], ['longboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodictasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortboard_id', sa.Integer(), nullable=True),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('task_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shortboard_id'], ['shortboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodictasks')
    op.drop_table('longtasks')
    op.drop_table('usersboardslink')
    op.drop_table('shortboard')
    op.drop_table('longboard')
    op.drop_table('user')
    op.drop_table('board')
    # ### end Alembic commands ###
