services:
  finance:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - parser
    environment:
      DATABASE_URL: postgresql://postgres:1234@localhost:5432/finance_db
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  parser:
    build:
      context: .
      dockerfile: parsing/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:1234@localhost:5432/finance_db
    command: python -m uvicorn call_parser:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"