version: '3'

services:
  web:
    image: finimage:latest

    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: finance_db
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - my_network

  parser:
    container_name: parser
    image: parsimage:latest
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_NAME: finance_db
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  my_network:
