site_name: Лабораторная работа 1

theme:
  name: material

nav:
  - Главная страница: index.md
  - Аутентификация: auth.md
  - База данных: db.md
  - Эндпоинты: endpoints.md
  - Схемы: schemas.md
  - Приложение: main.md