site_name: "Малютина Екатерина K33402"
nav:
  - "№1: Реализация серверного приложения FastAPI":
      - index.md
      - pr1.md
      - lab1.md
      - leetcode.md
  - "№2: Потоки. Процессы. Асинхронность.":
      - lr2.md
      - leetcode2.md
