site_name: "Лабораторные работы"
theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Переключиться на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Переключиться на светлую тему
  language: ru
repo_url: https://github.com/pankovakris/ITMO_ICT_WebDevelopment_tools_2023-2024/tree/lab-1
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox:
      auto_caption: true
extra_css:
- css/custom.css
- css/palette.scss
nav:
  - index.md
  - "№1: Lab 1":
      - lab_1/practice_1_3.md
      - lab_1/auth.md
      - lab_1/finance_models.md
      - lab_1/user_models.md
      - lab_1/endpoints.md

