"""empty message

Revision ID: 2ca9c04c1550
Revises: eb41fefa092e
Create Date: 2024-03-09 03:11:40.418999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca9c04c1550'
down_revision: Union[str, None] = 'eb41fefa092e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'other_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('other_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
