"""empty message

Revision ID: eb41fefa092e
Revises: 792a63a94fe9
Create Date: 2024-03-09 03:05:04.684079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb41fefa092e'
down_revision: Union[str, None] = '792a63a94fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('details', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'username')
    op.drop_column('trips', 'details')
    # ### end Alembic commands ###
