"""request add response

Revision ID: b3df0ef1a6d3
Revises: 
Create Date: 2024-03-18 15:21:20.598004

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3df0ef1a6d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('requests', 'conditions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('requests', 'conditions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('requests', 'response')
    # ### end Alembic commands ###
