site_name: Volgin Leonid K33391 labs
nav:
  -  ЛР №1:
      - lr1.md
  -  ПР №1.1:
      - pr1-1.md
  -  ПР №1.2:
      - pr1-2.md
  -  ПР №1.3:
      - pr1-3.md
  - ЛР №2:
      - lr2.md
  - ЛР №3:
      - lr3.md
  - Литкод:
      - leetk.md
