# Dockerfile.parser

FROM python:3.10

WORKDIR /BookCrossing

# Установка зависимостей парсера
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы парсера
COPY . .

# Определяем команду для запуска парсера
CMD ["python", "asynctask.py"]
