version: "3.10"
services:
  postgres:
    image: postgres:14.12
    environment:
      POSTGRES_DB: bookcrossing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5431:5431"