"""models upd

Revision ID: 7dc39b0b5f70
Revises: 658815db57de
Create Date: 2024-05-30 12:35:02.387427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7dc39b0b5f70'
down_revision: Union[str, None] = '658815db57de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookownership', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookownership', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookownership', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('bookownership', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
