"""Initial migration

Revision ID: 9719268a308d
Revises: 06cdac7d7b95
Create Date: 2024-03-19 12:54:53.093614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9719268a308d'
down_revision: Union[str, None] = '06cdac7d7b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tripreview', 'trip', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'tripreview', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userinterest', 'interest', ['interest_id'], ['id'])
    op.create_foreign_key(None, 'userinterest', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userprofile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.drop_constraint(None, 'userinterest', type_='foreignkey')
    op.drop_constraint(None, 'userinterest', type_='foreignkey')
    op.drop_constraint(None, 'tripreview', type_='foreignkey')
    op.drop_constraint(None, 'tripreview', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    # ### end Alembic commands ###
