"""author's country added

Revision ID: 347984ba9779
Revises: 
Create Date: 2024-03-24 23:07:36.545450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '347984ba9779'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_library', sa.Column('book_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_library', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_library', type_='foreignkey')
    op.drop_column('user_library', 'book_id')
    op.alter_column('book', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('author', 'country')
    # ### end Alembic commands ###
