"""fix all

Revision ID: 578a3aafe6df
Revises: 2296c25b9e51
Create Date: 2024-04-01 19:49:13.044215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '578a3aafe6df'
down_revision: Union[str, None] = '2296c25b9e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_author_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('book_author_id_fkey', 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###
