"""fix genre

Revision ID: 7d6840eab56d
Revises: 578a3aafe6df
Create Date: 2024-04-01 21:42:11.312344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d6840eab56d'
down_revision: Union[str, None] = '578a3aafe6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'genre',
               existing_type=postgresql.ENUM('Fiction', 'NonFiction', 'Mystery', 'Romance', 'ScienceFiction', name='bookgenre'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'genre',
               existing_type=postgresql.ENUM('Fiction', 'NonFiction', 'Mystery', 'Romance', 'ScienceFiction', name='bookgenre'),
               nullable=False)
    # ### end Alembic commands ###
