version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty@postgres:5432/bookcrossing_db

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: bookcrossing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty@postgres:5432/bookcrossing_db
      - PYTHONPATH=/BookCrossing
