services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pwd
      - POSTGRES_DB=api
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    ports:
      - 3000:8000
    depends_on:
      - db
    command: poetry run python -m uvicorn src.web_api.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    expose:
      - 6379
    restart: always

  url_parser:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run celery -A src.url_parser.main  worker --loglevel=info
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - api
