#version: '3.8'
#
#services:
#  db:
#    image: postgres:16.2
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 12345
#      POSTGRES_USER: postgres
#      POSTGRES_DB: lab1
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data:

version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: lab1
    ports:
      - "6000:5432"