version: '3.8'

services:
  api:
    container_name: trip_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn web_api.main:app --reload --host 0.0.0.0
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      DB_HOST: "db"
    depends_on:
      - db

  db:
    container_name: trip_fastapi_postgres 
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile 
    command: celery -A url_parser.main worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
    
volumes:
  postgres_data: