import sqlmodel
"""smt

Revision ID: 08d29f3c9f1c
Revises: 3f385e9d5f3b
Create Date: 2024-03-10 13:41:20.220940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d29f3c9f1c'
down_revision: Union[str, None] = '3f385e9d5f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
