import sqlmodel
"""smt

Revision ID: 0cd52f80a89d
Revises: 4583bbe3405b
Create Date: 2024-03-10 22:14:27.882631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd52f80a89d'
down_revision: Union[str, None] = '4583bbe3405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
