import sqlmodel
"""smt

Revision ID: 0e393a70a2e1
Revises: cfa26c422bb1
Create Date: 2024-03-10 13:04:11.594361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e393a70a2e1'
down_revision: Union[str, None] = 'cfa26c422bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
