import sqlmodel
"""smt

Revision ID: 3f385e9d5f3b
Revises: 0e393a70a2e1
Create Date: 2024-03-10 13:38:16.883794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f385e9d5f3b'
down_revision: Union[str, None] = '0e393a70a2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
