import sqlmodel
"""smt

Revision ID: 6e9e89f135ac
Revises: 1e5212ded2de
Create Date: 2024-03-09 15:01:01.176614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9e89f135ac'
down_revision: Union[str, None] = '1e5212ded2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
