import sqlmodel
"""smt

Revision ID: 748b09ce5ff3
Revises: 43c805aad95b
Create Date: 2024-03-09 17:47:45.418681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748b09ce5ff3'
down_revision: Union[str, None] = '43c805aad95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
