import sqlmodel
"""smt

Revision ID: 880d405cfb8e
Revises: c8a1e9aac899
Create Date: 2024-03-10 22:09:16.922057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880d405cfb8e'
down_revision: Union[str, None] = 'c8a1e9aac899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
