import sqlmodel
"""smt

Revision ID: 88933b4a675d
Revises: a67a1e2ed810
Create Date: 2024-03-09 17:53:42.768623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88933b4a675d'
down_revision: Union[str, None] = 'a67a1e2ed810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
