"""add travel models

Revision ID: c7b6c3188f65
Revises: 342f3032da8f
Create Date: 2024-05-17 16:42:09.857176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c7b6c3188f65'
down_revision: Union[str, None] = '342f3032da8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel',
    sa.Column('location_from_id', sa.Integer(), nullable=True),
    sa.Column('location_to_id', sa.Integer(), nullable=True),
    sa.Column('path_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('type_of_travel', sa.Enum('elite_hotel', 'pretty_simple_hotel', 'apartments', 'tents', name='typeoftravel'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_from_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['location_to_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel')
    # ### end Alembic commands ###
