"""add columns

Revision ID: 86f1b0cffc9d
Revises: ed0237c1209d
Create Date: 2024-05-30 16:21:09.453852

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f1b0cffc9d'
down_revision: Union[str, None] = 'ed0237c1209d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('is_approval', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'is_approval')
    # ### end Alembic commands ###
