"""add columns

Revision ID: 9179c04f1a0b
Revises: 86f1b0cffc9d
Create Date: 2024-05-30 17:26:38.901747

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9179c04f1a0b'
down_revision: Union[str, None] = '86f1b0cffc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'is_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'is_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
