version: '3.8'

services:
  web:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
      - worker

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web
    ports:
      - "8081:8081"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    command: celery -A app.celery_app worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - redis

volumes:
  postgres_data:



