"""edited relationships

Revision ID: 9c4b39bbb13b
Revises: b61623f1e263
Create Date: 2024-03-06 19:36:50.968082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c4b39bbb13b'
down_revision: Union[str, None] = 'b61623f1e263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('step_trip_id_fkey', 'step', type_='foreignkey')
    op.drop_constraint('step_transition_id_fkey', 'step', type_='foreignkey')
    op.drop_constraint('step_stay_id_fkey', 'step', type_='foreignkey')
    op.create_foreign_key(None, 'step', 'stay', ['stay_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step', 'transition', ['transition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'step', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('usertriplink_trip_id_fkey', 'usertriplink', type_='foreignkey')
    op.drop_constraint('usertriplink_user_id_fkey', 'usertriplink', type_='foreignkey')
    op.create_foreign_key(None, 'usertriplink', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usertriplink', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertriplink', type_='foreignkey')
    op.drop_constraint(None, 'usertriplink', type_='foreignkey')
    op.create_foreign_key('usertriplink_user_id_fkey', 'usertriplink', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usertriplink_trip_id_fkey', 'usertriplink', 'trip', ['trip_id'], ['id'])
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.create_foreign_key('step_stay_id_fkey', 'step', 'stay', ['stay_id'], ['id'])
    op.create_foreign_key('step_transition_id_fkey', 'step', 'transition', ['transition_id'], ['id'])
    op.create_foreign_key('step_trip_id_fkey', 'step', 'trip', ['trip_id'], ['id'])
    # ### end Alembic commands ###
